### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by njmattes** [RDCEP/EDE#13]
@ricardobarroslourenco @legendOfZelda I think it might be time to refactor this rdcep/ede repo to include the various bits of code that have been worked on over the last few weeks.  I propose we start a `refactor` branch of this repo, and start collecting all the changes that have been made elsewhere. I know we've stubbed out new models and API endpoints that all should be added into this `refactor` branch. 

Since we're forked from Plenario, perhaps we need to keep their MIT license? Their license is here: https://github.com/UrbanCCD-UChicago/plenario/blob/master/LICENSE.

**Comment by njmattes** [comment]
This morning started a `develop` branch, and a [`refactor_0316` branch](https://github.com/RDCEP/EDE/tree/refactor_0316). I'll update the server with this, do some basic testing, and then merge it into `develop` and we can continue to work there. Hope to get that done today, but I have to teach this afternoon.

**Comment by legendOfZelda** [comment]
yep, need LICENSE, which is there in `refactor_0316`, good. time to get up to speed with git, certainly for me.

**Comment by njmattes** [comment]
I'm not a licensing whiz unfortunately. This license contains: `Copyright (c) 2014 The University of Chicago and DataMade`. Are we obligated by the MIT license to retain the original unmodified copyright holder? Anyone know what the best practice is here?

**Comment by legendOfZelda** [comment]
i think we should do it according to: http://programmers.stackexchange.com/questions/157968/how-to-manage-a-copyright-notice-in-an-open-source-project, i.e. according to the last 'code' block in the answer, i.e. just adding our copyright right under the existing and use 'Original work' / 'Modified work' to distinguish them.

**Comment by njmattes** [comment]
I like it. So, who *is* the (c) holder of the modified code after all? Does UChicago own the (c) on the work of its staff / faculty / students? Since the DePaul subaward is funding Ricardo and I, does DePaul's IP protocol factor in (DPU doesn't take (c) ownership from its staff / faculty / students)?

**Comment by ricardobarroslourenco** [comment]
Hi folks, sorry about the delay in answering. I'm through my final works so I've been extra busy. On my way of see DePaul should have some part on this, but actually I don't know how this works. I remember some licensing discussion with @abrizius some months ago about an UChicago office that deals with this. Perhaps we should get some guidance.

**Comment by legendOfZelda** [comment]
it's probably going to be

```
Original work Copyright (c) 2014 The University of Chicago and DataMade
Modified work Copyright (c) 2016 [***]
```

where `*** = The University of Chicago and DePaul University`
but of course let's get some guidance to be on the safe side.

**Comment by njmattes** [comment]
Last conversation I had with anyone at DePaul about this, the upshot was that DePaul wanted no ownership of intellectual property, and that the copyright / trademark / patent / etc. was wholly owned by the individual. We could always double check with [ORS](http://offices.depaul.edu/ors/Pages/default.aspx).

**Comment by njmattes** [comment]
The basic refactoring is done, and has been merged with the `develop` branch. I'm closing this issue, and will open another for copyright issues. And perhaps another for more fundamental licensing questions.
