### ISSUE TITLE
Metadata table(s)

### ISSUE THREAD

**Issue by njmattes** [RDCEP/EDE#15]
@legendOfZelda In the current db, there's a `netcdf_meta` table that stores a JSON representation of the metadata from the original NetCDF file. I thought we were including these JSON blobs in the `global_meta` table, along with a `filetype` column, since a variety of filetypes will have metadata that needs storing. 

I bring it up mostly because it affects the code in the API. In some ways it doesn't really mater to me how we store the info (though my gut says to use the latter method).

**Comment by legendOfZelda** [comment]
yes, i'll put the JSON blob into `global_meta` and get rid of `netcdf_meta`. i will have to reingest the netcdfs and for that reason won't ingest many, say only a dozen or so, just for testing purposes. i wanted to do a big ingest to see whether my ingestion script can handle all these netcdfs (though they really seem to be of the same kind, or better: of one of two kinds).

**Comment by njmattes** [comment]
Yep, makes perfect sense.

**Comment by legendOfZelda** [comment]
i want to commit my changes soon but would be glad to resolve this #17 first.

**Comment by legendOfZelda** [comment]
done, see latest commit(s) to `develop` branch : fa6e459533d29cf58c0cbdacad32e8a8f1f21615
