### ISSUE TITLE
Name of id columns on database tables

### ISSUE THREAD

**Issue by njmattes** [RDCEP/EDE#19]
@legendOfZelda Is it possible to change the database schema so that each table's `primary_key` is called `id` (rather than eg `gid`)? `ForeignKeys` would still take names like `gid` to distinguish themselves. See the following files in the [`db_ids` branch](https://github.com/RDCEP/EDE/tree/db_ids) for a sense of what I'm talking about:

* [`ede/database.py:18–29`](https://github.com/RDCEP/EDE/blob/db_ids/ede/database.py)
* [`ede/schema/models.py`](https://github.com/RDCEP/EDE/blob/db_ids/ede/schema/models.py)

**Comment by legendOfZelda** [comment]
i haven't used `id` so far because it's a keyword in python

**Comment by njmattes** [comment]
Fair enough. How about `uid` then, and perhaps slightly more verbose foreign key names. See the last commit on the `db_ids` branch ([here](https://github.com/RDCEP/EDE/blob/db_ids/ede/database.py) and [here](https://github.com/RDCEP/EDE/blob/db_ids/ede/schema/models.py)).

**Comment by legendOfZelda** [comment]
yes, I'm fine with [your schema](https://github.com/RDCEP/EDE/blob/db_ids/ede/schema/models.py). only minor suggestions:

* i want to call the object `Grid_Var` (singular) but the underlying table `grid_vars` (plural) because the object really stands for one row, thus singular
* similarly, i want to use `var_id` instead of `vars_id`

**Comment by njmattes** [comment]
I'm fine with that. We should rip out the `@declared_attr` of the `EDEBase` object, and add `__table_name__`s back to the model objects. Do you want to do this refactor or want me to? I'm happy to do it—or to stay out of the way.

**Comment by legendOfZelda** [comment]
i'll do it now

**Comment by njmattes** [comment]
Works for me.
