### ISSUE TITLE
Documentation - UML Diagrams, Data Model and so on...

### ISSUE THREAD

**Issue by ricardobarroslourenco** [RDCEP/EDE#27]
@njmattes @legendOfZelda @abrizius
Today after our meeting, I'll start to summarize our efforts at EDE. The idea is to have considered on our diagrams:

- Current Data Model (and revisions);
- Component Architecture Diagram;
- Our use cases, and the components involved;
- Others (please suggest);

I think this would help to set goals, dues, and to keep on track during our development. I personally miss a graphical representation of our data model.

I'm intending to use [Dia](https://wiki.gnome.org/Apps/Dia), but I'm open to other tools. @njmattes do you know any other tool for *nix? (prior to open source development I just used ERwin, which is proprietary)

**Comment by njmattes** [comment]
Check out [yED](https://www.yworks.com/products/yed).

**Comment by legendOfZelda** [comment]
It's about time I read this :) I'm using yED.

**Comment by legendOfZelda** [comment]
It's about time I read this :) I'm using yED.

**Comment by ghost** [comment]
It's about time I read this :) I'm using Dia.
