### ISSUE TITLE
Return metadata uid's in API response

### ISSUE THREAD

**Issue by njmattes** [RDCEP/EDE#29]
@legendOfZelda We need to also return the `uid` for each metadata object when users make requests to `/api/v0/metadata/<intlist>`. This is so the `uid` exists on the frontend and can be added to future requests.

**Comment by legendOfZelda** [comment]
but the `intlist` in `/api/v0/metadata/<intlist>` already contains the `uid`'s so the users already need to know them prior to issuing `/api/v0/metadata/<intlist>`. so we should rather return the `uid`'s already in the response of a `/api/v0/metadata/` request

**Comment by njmattes** [comment]
We need to return them for `/api/v0/metadata/`, and for the sake of symmetry (and validation) we should return them for /api/v0/metadata/<intlist>` as well. Also because it's not transparent that if I request `3,7,1` if those are returned in the order requested, or in ascending order, or in the order their keys were last accessed in the db, etc.

**Comment by legendOfZelda** [comment]
@njmattes just wanted to tell you that i put back the:

* 'request' and 'response'
* 'units'
* requested 'url'

fields into the response json.

**Comment by njmattes** [comment]
Righteous. I've got some changes to the API locally that haven't been pushed yet. I just finished the bulk of my duties for these ongoing faculty searches, so should be back to EDE / ATLAS this week. Which branch are these changes on? I'll merge before I push everything.

**Comment by legendOfZelda** [comment]
in 'severin' and already merged into 'develop'

**Comment by njmattes** [comment]
Ah cool. I'll just pull and merge then. Thanks.
